version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: npm building
          command: |
            npm install
            CI=true npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: npm testing
          command: |
            npm install
            npm run test
  hithere:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: useless
          command: |
            echo "heloooo"
workflows:
    build_test_and_lint:
      jobs:
        - build
        - hithere
        - test:
            requires:
              - hithere
